//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoViewerApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoViewerApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        internal static string SearchTextErrorMessage
        {
            get
            {
                return ResourceManager.GetString("SearchTextErrorMessage", resourceCulture);
            }
        }

        internal static string SearchTextCaption
        {
            get
            {
                return ResourceManager.GetString("SearchTextCaption", resourceCulture);
            }
        }

        internal static string NumOfPhotosZeroErrorMessage
        {
            get
            {
                return ResourceManager.GetString("NumOfPhotosZeroErrorMessage", resourceCulture);
            }
        }

      
        internal static string NumOfPhotosCaption
        {
            get
            {
                return ResourceManager.GetString("NumOfPhotosCaption", resourceCulture);
            }
        }

        internal static string PhotosDownloadingMessage
        {
            get
            {
                return ResourceManager.GetString("PhotosDownloadingMessage", resourceCulture);
            }
        }
        internal static string NumOfPhotosExceed
        {
            get
            {
                return ResourceManager.GetString("NumOfPhotosExceed", resourceCulture);
            }
        }
        internal static string AuthenticationError
        {
            get
            {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        internal static string AuthenticationErrorCaption
        {
            get
            {
                return ResourceManager.GetString("AuthenticationErrorCaption", resourceCulture);
            }
        }
        internal static string TwitterAuthenticationError
        {
            get
            {
                return ResourceManager.GetString("TwitterAuthenticationError", resourceCulture);
            }
        }
        internal static string TwitterAuthenticationErrorCaption
        {
            get
            {
                return ResourceManager.GetString("TwitterAuthenticationErrorCaption", resourceCulture);
            }
        }
        internal static string NoTweetsMessage
        {
            get
            {
                return ResourceManager.GetString("NoTweetsMessage", resourceCulture);
            }
        }
        internal static string NoTweetsCaptionMessage
        {
            get
            {
                return ResourceManager.GetString("NoTweetsCaptionMessage", resourceCulture);
            }
        }
        internal static string NoPhotosMessage
        {
            get
            {
                return ResourceManager.GetString("NoPhotosMessage", resourceCulture);
            }
        }
        internal static string NoPhotosCaptionMessage
        {
            get
            {
                return ResourceManager.GetString("NoPhotosCaptionMessage", resourceCulture);
            }
        }
    }
}
